### ISSUE TITLE
Crash when exit app

### ISSUE THREAD

**Issue by XinyueZ** [XinyueZ/mvvm-template#2]
```
FATAL EXCEPTION: main
                                               Process: com.template.mvvm, PID: 892
                                               java.lang.RuntimeException: Unable to destroy activity {com.template.mvvm/com.template.mvvm.home.HomeActivity}: java.lang.IllegalStateException: Can't access ViewModels from onDestroy
                                                   at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4634)
                                                   at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4661)
                                                   at android.app.ActivityThread.-wrap7(ActivityThread.java)
                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                   at android.os.Looper.loop(Looper.java:154)
                                                   at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                Caused by: java.lang.IllegalStateException: Can't access ViewModels from onDestroy
                                                   at android.arch.lifecycle.HolderFragment$HolderFragmentManager.findHolderFragment(HolderFragment.java:136)
                                                   at android.arch.lifecycle.HolderFragment$HolderFragmentManager.holderFragmentFor(HolderFragment.java:155)
                                                   at android.arch.lifecycle.HolderFragment.holderFragmentFor(HolderFragment.java:81)
                                                   at android.arch.lifecycle.ViewModelStores.of(ViewModelStores.java:43)
                                                   at android.arch.lifecycle.ViewModelProviders.of(ViewModelProviders.java:121)
                                                   at com.template.mvvm.ext.ViewModelExtKt.obtainViewModel(ViewModelExt.kt:26)
                                                   at com.template.mvvm.AppBaseFragment.obtainViewModel(AppBaseFragment.kt:8)
                                                   at com.template.mvvm.home.AllGendersFragment.onDetach(AllGendersFragment.kt:48)
                                                   at android.support.v4.app.Fragment.performDetach(Fragment.java:2526)
                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1563)
                                                   at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                   at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
                                                   at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3218)
                                                   at android.support.v4.app.Fragment.performDestroy(Fragment.java:2511)
                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1557)
                                                   at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                   at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3227)
                                                   at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3218)
                                                   at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:262)
                                                   at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:362)
                                                   at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:209)
                                                   at android.app.Activity.performDestroy(Activity.java:7210)
                                                   at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1161)
                                                   at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4621)
                                                   at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4661) 
                                                   at android.app.ActivityThread.-wrap7(ActivityThread.java) 
                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703) 
                                                   at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                   at android.os.Looper.loop(Looper.java:154) 
                                                   at android.app.ActivityThread.main(ActivityThread.java:6776) 
                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 
```

**Comment by XinyueZ** [comment]
fixed
